-- Generated by pgslice
-- Date: 2025-12-29T11:56:27.238674
-- Records: 6
-- Mode: PL/pgSQL with ID remapping

-- Create temporary table for ID mapping
CREATE TEMP TABLE IF NOT EXISTS _pgslice_id_map (
    table_name TEXT NOT NULL,
    old_id TEXT NOT NULL,
    new_id TEXT NOT NULL,
    PRIMARY KEY (table_name, old_id)
);

-- Main PL/pgSQL block with ID remapping
DO $$
DECLARE
    v_new_id_staff integer;
    v_new_ids_staff integer[];
    v_old_ids_staff TEXT[];
    v_new_id_country integer;
    v_new_ids_country integer[];
    v_old_ids_country TEXT[];
    v_new_id_city integer;
    v_new_ids_city integer[];
    v_old_ids_city TEXT[];
    v_new_id_store integer;
    v_new_ids_store integer[];
    v_old_ids_store TEXT[];
    v_new_id_address integer;
    v_new_ids_address integer[];
    v_old_ids_address TEXT[];
    i INTEGER;
BEGIN

    -- Table: "public"."country" (1 records)
    INSERT INTO "public"."country" ("country", "last_update")
    VALUES
        ('Canada', '2006-02-15T09:44:00')
    RETURNING country_id INTO v_new_id_country;
    INSERT INTO _pgslice_id_map VALUES ('"public"."country"', '20', v_new_id_country::TEXT);

    -- Table: "public"."city" (1 records)
    INSERT INTO "public"."city" ("city", "country_id", "last_update")
    SELECT
        data.city::character varying,
        map0.new_id::smallint,
        data.last_update::timestamp without time zone
    FROM (VALUES
        ('Lethbridge', '20', '2006-02-15T09:45:25')
    ) AS data(city, old_country_id, last_update)
    JOIN _pgslice_id_map map0
        ON map0.table_name = '"public"."country"'
        AND map0.old_id = data.old_country_id
    RETURNING city_id INTO v_new_id_city;
    INSERT INTO _pgslice_id_map VALUES ('"public"."city"', '300', v_new_id_city::TEXT);

    -- Table: "public"."address" (2 records)
    v_old_ids_address := ARRAY['1', '3'];
    WITH inserted AS (
        INSERT INTO "public"."address" ("address", "address2", "city_id", "district", "last_update", "phone", "postal_code")
        SELECT
            data.address::character varying,
        data.address2::character varying,
        map0.new_id::smallint,
        data.district::character varying,
        data.last_update::timestamp without time zone,
        data.phone::character varying,
        data.postal_code::character varying
        FROM (VALUES
            ('47 MySakila Drive', NULL, '300', 'Alberta', '2006-02-15T09:45:30', '', ''),
        ('23 Workhaven Lane', NULL, '300', 'Alberta', '2006-02-15T09:45:30', '14033335568', '')
        ) AS data(address, address2, old_city_id, district, last_update, phone, postal_code)
        JOIN _pgslice_id_map map0
        ON map0.table_name = '"public"."city"'
        AND map0.old_id = data.old_city_id
        RETURNING address_id
    )
    SELECT array_agg(address_id) INTO v_new_ids_address FROM inserted;
    
    FOR i IN 1..array_length(v_new_ids_address, 1) LOOP
        INSERT INTO _pgslice_id_map VALUES ('"public"."address"', v_old_ids_address[i], v_new_ids_address[i]::TEXT);
    END LOOP;

    -- Table: "public"."staff" (1 records)
    INSERT INTO "public"."staff" ("active", "address_id", "email", "first_name", "last_name", "last_update", "password", "picture", "store_id", "username")
    SELECT
        data.active::boolean,
        map0.new_id::smallint,
        data.email::character varying,
        data.first_name::character varying,
        data.last_name::character varying,
        data.last_update::timestamp without time zone,
        data.password::character varying,
        data.picture::bytea,
        data.store_id::smallint,
        data.username::character varying
    FROM (VALUES
        (TRUE, '3', 'Mike.Hillyer@sakilastaff.com', 'Mike', 'Hillyer', '2006-05-16T16:13:11.793280', '8cb2237d0679ca88db6464eac60da96345513964', '\x89504e470d0a5a0a', 1, 'Mike')
    ) AS data(active, old_address_id, email, first_name, last_name, last_update, password, picture, store_id, username)
    JOIN _pgslice_id_map map0
        ON map0.table_name = '"public"."address"'
        AND map0.old_id = data.old_address_id
    RETURNING staff_id INTO v_new_id_staff;
    INSERT INTO _pgslice_id_map VALUES ('"public"."staff"', '1', v_new_id_staff::TEXT);

    -- Table: "public"."store" (1 records)
    INSERT INTO "public"."store" ("address_id", "last_update", "manager_staff_id")
    SELECT
        map0.new_id::smallint,
        data.last_update::timestamp without time zone,
        map1.new_id::smallint
    FROM (VALUES
        ('1', '2006-02-15T09:57:12', '1')
    ) AS data(old_address_id, last_update, old_manager_staff_id)
    JOIN _pgslice_id_map map0
        ON map0.table_name = '"public"."address"'
        AND map0.old_id = data.old_address_id
    JOIN _pgslice_id_map map1
        ON map1.table_name = '"public"."staff"'
        AND map1.old_id = data.old_manager_staff_id
    RETURNING store_id INTO v_new_id_store;
    INSERT INTO _pgslice_id_map VALUES ('"public"."store"', '1', v_new_id_store::TEXT);

END $$;

-- Cleanup
DROP TABLE IF EXISTS _pgslice_id_map;
